//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int MACHITIET { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> MADH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> Tongtien { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual OrderPro OrderPro { get; set; }
    }
}
